module Zxcvbn
  class PasswordTooLong < ArgumentError
  end

  VERSION: String

  type user_inputs = Array[String]

  def self.test: (String? password, ?user_inputs user_inputs) -> Score

  def self.tester: () -> TesterBuilder
end
