module Zxcvbn
  module CrackTime
    ATTACK_SCENARIOS: Hash[String, Float]

    def estimate_attack_times: (Numeric guesses) -> { crack_times_seconds: Hash[String, Float], crack_times_display: Hash[String, String] }

    def guesses_to_score: (Numeric guesses) -> Integer

    def display_time: (Numeric seconds) -> String
  end
end
