module Zxcvbn
  class Data
    type ranked_dictionary = Hash[String, Integer]
    type adjacency_graph = Hash[String, Array[String?]]
    type graph_stats = Hash[String, { average_degree: Float, starting_positions: Integer }]

    class Dictionaries
      attr_reader ranked: Hash[String, ranked_dictionary]
      attr_reader tries: Hash[String, Trie]

      def initialize: (ranked: Hash[String, ranked_dictionary], tries: Hash[String, Trie]) -> void
    end

    @dictionaries: Dictionaries
    @adjacency_graphs: Hash[String, adjacency_graph]
    @graph_stats: graph_stats

    attr_reader dictionaries: Dictionaries
    attr_reader adjacency_graphs: Hash[String, adjacency_graph]
    attr_reader graph_stats: graph_stats

    def ranked_dictionaries: () -> Hash[String, ranked_dictionary]

    def dictionary_tries: () -> Hash[String, Trie]

    def initialize: () -> void

    def add_word_list: (String name, Array[String] list) -> void

    private

    def read_word_list: (String file) -> Array[String]

    def build_tries: (Hash[String, ranked_dictionary] ranked) -> Hash[String, Trie]

    def compute_graph_stats: () -> graph_stats
  end
end
