module Zxcvbn
  class Feedback < Data
    attr_reader warning: String
    attr_reader suggestions: Array[String]

    def initialize: (?warning: String, ?suggestions: Array[String]) -> void
  end
end
