module Zxcvbn
  module Guesses
    MIN_GUESSES_BEFORE_GROWING_SEQUENCE: Integer
    MIN_SUBMATCH_GUESSES_SINGLE_CHAR: Integer
    MIN_SUBMATCH_GUESSES_MULTI_CHAR: Integer
    BRUTEFORCE_CARDINALITY: Integer
    MIN_YEAR_SPACE: Integer

    START_UPPER: Regexp
    END_UPPER: Regexp
    ALL_UPPER: Regexp
    ALL_LOWER: Regexp

    attr_reader reference_year: Integer

    def estimate_guesses: (MatchBuilder match, String password) -> Numeric

    def bruteforce_guesses: (MatchBuilder match) -> Numeric

    def sequence_guesses: (MatchBuilder match) -> Numeric

    def digits_guesses: (MatchBuilder match) -> Integer

    def year_guesses: (MatchBuilder match) -> Integer

    def date_guesses: (MatchBuilder match) -> Numeric

    def spatial_guesses: (MatchBuilder match) -> Numeric

    def dictionary_guesses: (MatchBuilder match) -> Numeric

    def uppercase_variations: (MatchBuilder match) -> Integer

    def l33t_variations: (MatchBuilder match) -> Integer
  end
end
