module Zxcvbn
  class Match < Data
    attr_reader pattern: String?
    attr_reader i: Integer?
    attr_reader j: Integer?
    attr_reader token: String?
    attr_reader matched_word: String?
    attr_reader rank: Integer?
    attr_reader dictionary_name: String?
    attr_reader reversed: bool?
    attr_reader l33t: bool?
    attr_reader sub: Hash[String, String]?
    attr_reader sub_display: String?
    attr_reader guesses: Numeric?
    attr_reader guesses_log10: Float?
    attr_reader base_guesses: Numeric?
    attr_reader uppercase_variations: Numeric?
    attr_reader l33t_variations: Numeric?
    attr_reader base_token: String?
    attr_reader repeat_count: Integer?
    attr_reader sequence_name: String?
    attr_reader sequence_space: Integer?
    attr_reader ascending: bool?
    attr_reader graph: String?
    attr_reader turns: Integer?
    attr_reader shifted_count: Integer?
    attr_reader year: Integer?
    attr_reader month: Integer?
    attr_reader day: Integer?
    attr_reader separator: String?

    def initialize: (?pattern: String?, ?i: Integer?, ?j: Integer?, ?token: String?, ?matched_word: String?, ?rank: Integer?, ?dictionary_name: String?, ?reversed: bool?, ?l33t: bool?, ?sub: Hash[String, String]?, ?sub_display: String?, ?guesses: Numeric?, ?guesses_log10: Float?, ?base_guesses: Numeric?, ?uppercase_variations: Numeric?, ?l33t_variations: Numeric?, ?base_token: String?, ?repeat_count: Integer?, ?sequence_name: String?, ?sequence_space: Integer?, ?ascending: bool?, ?graph: String?, ?turns: Integer?, ?shifted_count: Integer?, ?year: Integer?, ?month: Integer?, ?day: Integer?, ?separator: String?) -> void

    def with: (**untyped) -> Match

    def inspect: () -> String

    def pretty_print: (untyped pp) -> void
  end
end
