module Zxcvbn
  class PasswordStrength
    @omnimatch: Omnimatch
    @scorer: Scorer

    def initialize: (Data data) -> void

    def test: (String? password, ?Array[untyped] user_inputs) -> Score
  end
end
