module Zxcvbn
  class Score < ::Data
    def self.new: (
      password: String,
      guesses: Numeric,
      sequence: Array[Match],
      crack_times_seconds: Hash[String, Float],
      crack_times_display: Hash[String, String],
      score: Integer,
      ?calc_time: Float?,
      ?feedback: Feedback?
    ) -> instance

    attr_reader password: String?
    attr_reader guesses: Numeric?
    attr_reader sequence: Array[Match]?
    attr_reader crack_times_seconds: Hash[String, Float]?
    attr_reader crack_times_display: Hash[String, String]?
    attr_reader score: Integer?
    attr_reader calc_time: Float?
    attr_reader feedback: Feedback?

    def guesses_log10: () -> Float?
    def with: (**untyped) -> instance
  end
end
