module Zxcvbn
  class Scorer
    include Guesses
    include CrackTime

    @data: Data
    @omnimatch: Omnimatch
    @reference_year: Integer
    @repeat_cache: Hash[String, Numeric]

    attr_reader data: Data

    def initialize: (Data data, Omnimatch omnimatch, Integer reference_year) -> void

    def most_guessable_match_sequence: (String password, Array[MatchBuilder] matches, ?exclude_additive: bool) -> Score

    def repeat_guesses: (MatchBuilder match) -> Numeric
  end
end
