module Zxcvbn
  class Scorer
    include Guesses
    include CrackTime

    @data: Data
    @omnimatch: Omnimatch

    attr_reader data: Data

    def initialize: (Data data, Omnimatch omnimatch) -> void

    def most_guessable_match_sequence: (String password, Array[Match] matches, ?exclude_additive: bool, ?user_inputs: Array[String]) -> Score

    def repeat_guesses: (Match match, ?user_inputs: Array[String]) -> Numeric
  end
end
