module Zxcvbn
  class Tester
    @data: Data
    @omnimatch: Omnimatch
    @max_password_length: Integer

    def initialize: (data: Data, max_password_length: Integer) -> void

    attr_reader max_password_length: Integer

    def test: (String? password, ?Array[untyped] user_inputs) -> Score

    def inspect: () -> String
  end
end
