module Zxcvbn
  class Trie
    type node = Hash[untyped, untyped]

    @root: node

    def self.from_ranked: (Data::ranked_dictionary ranked_dictionary) -> Trie

    def initialize: () -> void

    def insert: (String word, Integer rank) -> void

    def search_prefixes: (String text, Integer start_pos) -> Array[[String, Integer?, Integer, Integer]]
  end
end
